// Doc: https://firebase.google.com/docs/reference/js/auth#autherrorcodes
interface ErrorMessage {
  [key: string]: string;
}
const firebaseAuthErrorMessages: ErrorMessage = {
  "auth/admin-restricted-operation": "This operation is restricted to administrators.",
  "auth/argument-error": "Invalid argument was provided.",
  "auth/app-not-authorized": "The app is not authorized to use Firebase Authentication.",
  "auth/app-not-installed": "The app is not installed on the device.",
  "auth/captcha-check-failed": "The CAPTCHA check failed.",
  "auth/code-expired": "The verification code has expired.",
  "auth/cordova-not-ready": "Cordova framework is not ready.",
  "auth/cors-unsupported": "CORS (Cross-Origin Resource Sharing) is unsupported by the browser.",
  "auth/credential-already-in-use": "This credential is already associated with another user.",
  "auth/custom-token-mismatch": "The custom token does not match the Firebase project.",
  "auth/requires-recent-login": "Recent login required. Please reauthenticate.",
  "auth/dependent-sdk-initialized-before-auth": "A dependent SDK was initialized before Firebase Authentication.",
  "auth/dynamic-link-not-activated": "Firebase Dynamic Links are not activated.",
  "auth/email-already-in-use": "This email address is already in use by another account.",
  "auth/emulator-config-failed": "Failed to configure the Firebase Emulator.",
  "auth/expired-action-code": "The action code has expired.",
  "auth/cancelled-popup-request": "The popup request was canceled.",
  "auth/internal-error": "An internal error occurred.",
  "auth/invalid-api-key": "The API key provided is invalid.",
  "auth/invalid-app-credential": "The app credential provided is invalid.",
  "auth/invalid-app-id": "The app ID provided is invalid.",
  "auth/invalid-user-token": "The user's credential is no longer valid.",
  "auth/invalid-auth-event": "An invalid authentication event occurred.",
  "auth/invalid-cert-hash": "The certificate hash provided is invalid.",
  "auth/invalid-verification-code": "The verification code is invalid.",
  "auth/invalid-continue-uri": "The continue URL provided is invalid.",
  "auth/invalid-cordova-configuration": "The Cordova configuration is invalid.",
  "auth/invalid-custom-token": "The custom token is invalid.",
  "auth/invalid-dynamic-link-domain": "The dynamic link domain is invalid.",
  "auth/invalid-email": "The email address provided is invalid.",
  "auth/invalid-emulator-scheme": "The emulator scheme is invalid.",
  "auth/invalid-credential": "The credentials provided are invalid.",
  "auth/invalid-message-payload": "The message payload provided is invalid.",
  "auth/invalid-multi-factor-session": "The multi-factor session is invalid.",
  "auth/invalid-oauth-client-id": "The OAuth client ID is invalid.",
  "auth/invalid-oauth-provider": "The OAuth provider is invalid.",
  "auth/invalid-action-code": "The action code is invalid.",
  "auth/unauthorized-domain": "The domain is unauthorized.",
  "auth/wrong-password": "The password is incorrect.",
  "auth/invalid-persistence-type": "The persistence type provided is invalid.",
  "auth/invalid-phone-number": "The phone number provided is invalid.",
  "auth/invalid-provider-id": "The provider ID is invalid.",
  "auth/invalid-recipient-email": "The recipient email address is invalid.",
  "auth/invalid-sender": "The sender address is invalid.",
  "auth/invalid-verification-id": "The verification ID is invalid.",
  "auth/invalid-tenant-id": "The tenant ID provided is invalid.",
  "auth/multi-factor-info-not-found": "The multi-factor information was not found.",
  "auth/multi-factor-auth-required": "Multi-factor authentication is required.",
  "auth/missing-android-pkg-name": "The Android package name is missing.",
  "auth/missing-app-credential": "The app credential is missing.",
  "auth/auth-domain-config-required": "The authentication domain configuration is required.",
  "auth/missing-verification-code": "The verification code is missing.",
  "auth/missing-email": "The email address is missing.",
  "auth/missing-continue-uri": "The continue URL is missing.",
  "auth/missing-iframe-start": "The iframe start is missing.",
  "auth/missing-ios-bundle-id": "The iOS bundle ID is missing.",
  "auth/missing-or-invalid-nonce": "The nonce is missing or invalid.",
  "auth/missing-multi-factor-info": "The multi-factor information is missing.",
  "auth/missing-multi-factor-session": "The multi-factor session is missing.",
  "auth/missing-phone-number": "The phone number is missing.",
  "auth/missing-verification-id": "The verification ID is missing.",
  "auth/app-deleted": "The app has been deleted.",
  "auth/account-exists-with-different-credential": "An account exists with a different credential.",
  "auth/network-request-failed": "Network request failed. Please try again later.",
  "auth/null-user": "No user found.",
  "auth/no-auth-event": "No authentication event found.",
  "auth/no-such-provider": "The authentication provider does not exist.",
  "auth/operation-not-allowed": "This operation is not allowed.",
  "auth/operation-not-supported-in-this-environment": "This operation is not supported in this environment.",
  "auth/popup-blocked": "The popup was blocked by the browser.",
  "auth/popup-closed-by-user": "The popup was closed by the user.",
  "auth/provider-already-linked": "This provider is already linked to the account.",
  "auth/quota-exceeded": "Quota exceeded. Please try again later.",
  "auth/redirect-cancelled-by-user": "The redirect was canceled by the user.",
  "auth/redirect-operation-pending": "A redirect operation is already pending.",
  "auth/rejected-credential": "The credential was rejected.",
  "auth/second-factor-already-in-use": "The second factor is already in use.",
  "auth/maximum-second-factor-count-exceeded": "Maximum number of second factors exceeded.",
  "auth/tenant-id-mismatch": "The tenant ID does not match.",
  "auth/timeout": "The operation timed out. Please try again.",
  "auth/user-token-expired": "The user's token has expired.",
  "auth/too-many-requests": "Too many requests. Please try again later.",
  "auth/unauthorized-continue-uri": "Unauthorized continue URL.",
  "auth/unsupported-first-factor": "Unsupported first factor for authentication.",
  "auth/unsupported-persistence-type": "Unsupported persistence type.",
  "auth/unsupported-tenant-operation": "Unsupported tenant operation.",
  "auth/unverified-email": "The email address is not verified.",
  "auth/user-cancelled": "The user canceled the operation.",
  "auth/user-not-found": "No user found with this email.",
  "auth/user-disabled": "The user account is disabled.",
  "auth/user-mismatch": "The user credentials do not match.",
  "auth/user-signed-out": "The user has signed out.",
  "auth/weak-password": "The password provided is too weak.",
  "auth/web-storage-unsupported": "Web storage is unsupported in this environment.",
  "auth/already-initialized": "Firebase Auth has already been initialized.",
  "auth/recaptcha-not-enabled": "reCAPTCHA is not enabled.",
  "auth/missing-recaptcha-token": "The reCAPTCHA token is missing.",
  "auth/invalid-recaptcha-token": "The reCAPTCHA token is invalid.",
  "auth/invalid-recaptcha-action": "The reCAPTCHA action is invalid.",
  "auth/missing-client-type": "The client type is missing.",
  "auth/missing-recaptcha-version": "The reCAPTCHA version is missing.",
  "auth/invalid-recaptcha-version": "The reCAPTCHA version is invalid.",
  "auth/invalid-req-type": "The request type is invalid.",
};

export default firebaseAuthErrorMessages;
